### ISSUE TITLE
[patch] TypeError in noscript-spoof scriptlet with invalid meta refresh URL

### ISSUE THREAD

**Issue by vtriolet** [uBlockOrigin/uBlock-issues#1676]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

The noscript-spoof scriptlet passes meta refresh URLs to the URL constructor without any exception handling:

https://github.com/gorhill/uBlock/blob/1.37.3b2/src/js/scriptlets/noscript-spoof.js#L45

This can cause the scriptlet to trigger a TypeError when an invalid meta refresh URL like "http://foo@" is specified.  This uncaught exception prevents subsequent noscript nodes from being processed.

Proposed patch: https://github.com/vtriolet/uBlock/commit/2b9aba27489274a42bcc03ae7ac1da3bb33305a9

### A specific URL where the issue occurs

https://vtriolet.netlify.app/demos/ubo-invalid_meta_refresh_url.html

### Steps to Reproduce

1. Check the "Disable JavaScript" checkbox on the Settings page
2. Visit https://vtriolet.netlify.app/demos/ubo-invalid_meta_refresh_url.html
3. Notice that only the first noscript element has been transformed to a span

POC code for future reference:
```html
<!DOCTYPE html>
<html>
 <head>
  <title>uBO - invalid meta refresh URL</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
 </head>
 <body>
  <noscript><p>Node a should be visible</p></noscript>
  <noscript><meta http-equiv="refresh" content="15;url=https://foo@"></noscript>
  <noscript><p>Node b should also be visible</p></noscript> 
</body>
</html>

```

### Expected behavior

All noscript nodes should be processed.

### Actual behavior

Only the first noscript node is fully processed due to an uncaught TypeError:

```
Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at autoRefresh (noscript-spoof.js:45)
    at noscript-spoof.js:77
    at noscript-spoof.js:81
```

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 90.0.2, Chrome 92.0.4515.107

### Operating System and version

Arch Linux

**Comment by gorhill** [comment]
Thanks for finding and fixing the issue. I pulled your patch, <https://github.com/gorhill/uBlock/commit/2b9aba27489274a42bcc03ae7ac1da3bb33305a9>. This makes you a contributor and next time you can open a pull request in <https://github.com/gorhill/uBlock> directly.

**Comment by vtriolet** [comment]
Thanks, that sounds great.
