### ISSUE TITLE
Remove tracking parameters from URLs

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uBlock-issues#1724]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Some sites use tracking parameters in URLs to track users, which can lead to exposing user privacy, so I would like to add a new feature to remove these tracking parameters. adGuard has this feature.
However, each page may have different tracking parameters, which may require creating a new filter that records each page's tracking parameters and removes
I don't know if this is beyond the scope of uBO

### A specific URL where the issue occurs

_No need_

### Steps to Reproduce

_No need_

### Expected behavior

_No need_

### Actual behavior

_No need_

### uBlock Origin version

_No need_

### Browser name and version

_No need_

### Operating System and version

_No need_

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#removeparam

**Comment by shenzhiming88** [comment]
Sorry, I'm not good at English, so I didn't see this WIKI
Also, I don't seem to see these rules in any of the lists. So could uBO create a separate rule for clearing tracking parameters, or include it in the Privacy list?

**Comment by gorhill** [comment]
There is _"AdGuard URL Tracking Protection"_ in the stock filter lists.
