### ISSUE TITLE
[Enhancement] Add option to *automatically* visit embedded URLs w/o tracker

### ISSUE THREAD

**Issue by e-t-l** [uBlockOrigin/uBlock-issues#1784]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

This is related to #524, which discussed decoding the embedded target URL from a tracking link in order to visit the target URL directly. The author of that issue didn't realize that UBO already performs this function; however, I am opening this issue to request that an option be added to perform this function _automatically_.

### A specific URL where the issue occurs

`https://clickserve.dartsearch.net/link/click?lid=92700066828755385&ds_s_kwgid=58700007438573770&ds_s_inventory_feed_id=97700000008788619&ds_a_cid=593251564&ds_a_caid=14889755037&ds_a_agid=129004833835&ds_a_lid=pla-1435658028215&&ds_e_adid=79233728385239&ds_e_target_id=pla-4582833208586567&ds_e_product_group_id=4582833208586567&ds_e_product_id=238373&ds_e_product_country=US&ds_e_product_language=EN&ds_e_product_channel=Online&ds_e_network=s&ds_url_v=2&ds_dest_url=https://www.gamestop.com/electronics/cell-phones/accessories/microsd-cards/products/pny-512gb-elite-usb-3.1-gen-1c-flash-drive/238373.html?gclid=13edb60cb04f1f7c91b4d776002f80bd&gclsrc=3p.ds&msclkid=13edb60cb04f1f7c91b4d776002f80bd&utm_source=bing&utm_medium=cpc&utm_campaign=%24PLA_%24BNG_%24NB_Category_Electronics&utm_term=4582833208586567&utm_content=Electronics_All_Other_Products`

### Steps to Reproduce

1. Click a tracking link (like the example given above) that triggers the UBO redirect page that says, "uBlock Origin has prevented the following page from loading: [...]"
2. Click the symbol of the magnifying glass with a plus "+" in it.
3. Find the entry that says either `url =` or `ds_dest_url =` (or some other way the target URL is encoded), if it exists.
4. Find its subentry that says `without parameters =` if it exists.
5. Click on the URL following that entry.

### Expected behavior

Ideally, when the original link is clicked, UBO would automatically navigate to the tracker-free target URL. The UBO redirection page would not appear at all, and the user would not have to perform all the steps listed above.

### Actual behavior

[same as Steps to Reproduce]

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 1.38.6

### Operating System and version

Windows 10 Home

**Comment by imTHAI** [comment]
@gorhill 
I've seen it has been declined. Too bad. :(
But as you mentioned, some add-on do such filtering as [ClearURLs.](https://clearurls.xyz). And AdGuard also will implement it too (CoreLibs v1.11). 
Do you think they take unreasonable risk ? Or it's because their way of filtering is different and it's less dangerous for a reason I don't understand because I know nothing about all those filtering stuff ? 

Please, consider it as a real question, not a troll. I'd like to understand. (and english is not my native lang so I worry you misinterpret it)
Thank you

**Comment by gorhill** [comment]
AdGuard has concept of "trusted list", so I am guessing those redirect bypass filters will work only when present in a trusted list. I will introduce the concept of trusted list eventually as a solution to <https://github.com/uBlockOrigin/uBlock-issues/issues/1845>.

As for ClearURLs, from the [screenshot seen here](https://addons.mozilla.org/firefox/addon/clearurls/), it appears it's using its own rules, so they are of course trusted.

**Comment by imTHAI** [comment]
> AdGuard has concept of "trusted list", so I am guessing those redirect bypass filters will work only when present in a trusted list. 

You r right, the dev indeed said "the problem with it is that it can be rather dangerous. We might consider it for trusted filters, though."

> I will introduce the concept of trusted list eventually as a solution to #1845.

So after this concept will be introduced, you maybe will reconsider implementing the filtering we talked about here, I suppose correctly ?
Thank you.

**Comment by gorhill** [comment]
Yes, I will reconsider once trusted lists are a thing in uBO, and also depending on support at that point on AdGuard.

**Comment by imTHAI** [comment]
Thanks, I'll keep you posted about AdGuard. I follow it closely as I was the requestor.
