### ISSUE TITLE
make-webext-meta.py: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1860: ordinal not in range

### ISSUE THREAD

**Issue by apoleon** [uBlockOrigin/uBlock-issues#218]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The tools/make-webext-meta.py script raises an error in line 21.

Traceback (most recent call last):
  File "tools/make-webext-meta.py", line 21, in <module>
    webext_manifest = json.load(f2)
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1860: ordinal not in range(128)

This is caused by a non-ascii character in platform/webext/manifest.json.
It can be fixed by changing the line

with open(webext_manifest_file) as f2:

to

with open(webext_manifest_file, encoding="utf-8") as f2:

### A specific URL where the issue occurs

Not needed

### Steps to Reproduce

Run tools/make-webext.sh script after using set -e.

### Expected behavior:

Running tools/make-webext.sh produces no errors.

### Actual behavior:

The make-webext-meta.py scripts fails to run.

### Your environment

* uBlock Origin version: 1.16.14
* Browser Name and version: Firefox ESR 60
* Operating System and version: Debian GNU/Linux (Debian 10 "Buster)

**Comment by gorhill** [comment]
Fixed with <https://github.com/gorhill/uBlock/commit/a8c4e0214fa7f1fc3c4a721f89883f2538bbeb14>.
