### ISSUE TITLE
make-firefox-meta.py:24: SyntaxWarning: invalid escape sequence '\d'

### ISSUE THREAD

**Issue by glitsj16** [uBlockOrigin/uBlock-issues#3229]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

On my Arch Linux box with `python 3.12.3-1` I'm seeing the below when building the Firefox WE:

```sh
$ sh ./tools/make-firefox.sh
[...]
/home/glitsj16/ublock/tools/make-firefox-meta.py:24: SyntaxWarning: invalid escape sequence '\d'
  match = re.search('^(\d+\.\d+\.\d+)(\.\d+)$', version)
[...]
```

### A specific URL where the issue occurs.

```yaml
N/A
```

### Steps to Reproduce

1. Clone the repo
2. Build the Firefox WE

### Expected behavior

No SyntaxWarning(s)

### Actual behavior

SyntaxWarning

NOTE: probably also happens when building other (non-Firefox) WE's, but I didn't actually check that.

### uBO version

1.57.3.7

### Browser name and version

Firefox 125.0.4

### Operating System and version

Arch Linux

**Comment by stephenhawk8054** [comment]
@gorhill I think it needs raw string

```py
match = re.search(r'^(\d+\.\d+\.\d+)(\.\d+)$', version)
```

**Comment by smordarski** [comment]
I think that is due to the fact that Python 3.12.* does `SyntaxWarning` instead of `DeprecationWarning` for invalid backslash escape sequences. (I am a developer that does Python programming so I saw this error in one of my scripts) @stephenhawk8054 answer should work because using a raw string in my script worked.

This is a quote from Python's website:

> Invalid backslash escape sequences in strings now warn with SyntaxWarning instead of DeprecationWarning, making them more visible. (They will become syntax errors in the future.)

Link: https://www.python.org/downloads/release/python-3123/
