### ISSUE TITLE
Split repo is confusing, so combine issue tracker and source code repository again

### ISSUE THREAD

**Issue by rugk** [uBlockOrigin/uBlock-issues#3438]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

On https://github.com/gorhill/uBlock/issues/3726 you wrote to split the issue tracker from the code (only) because:

> Reason: the new issue tracker allows me to grant full permissions to volunteers in processing issues without having to grant full commit rights to code repository.

As of 2024 this is no longer needed, as GitHub allows for fine-grained controls, so only issue or code access e.g. can be given.

### A specific URL where the issue occurs.

```yaml
https://github.com/gorhill/uBlock/issues/3726
```

### Steps to Reproduce

Visit https://github.com/gorhill/uBlock/ / https://github.com/gorhill/uBlock/issues/3726

### Expected behavior

Usually, I expect the issue tracker to be at the same location as the source code, everything else is also not intuitive and breaks workflows such as linking and closing issues from commits/PRs and vice versa.

Actually, the reason is no longer valid as explained above. See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-teams-and-people-with-access-to-your-repository for details.
One can also configure it for an org (uBlockOrigin seems be an org already): https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization

BTW as for **migrating**, I'd propose to keep the issues here and just push the git repository (aka code) from the other one into here. This can be done with a few git commands. Then you can delete and rename the repositories (GitHub should keep redirects in place) and thus the way is not as hard. And you keep all old issues… (except from the old repository)

I mean you can also transfer issues (in an org) nowadays, but AFAIK only a single one at a time, so this would be time-consuming from clicks.

### Actual behavior

The code and issue are separated. As said, this may break features and also confuses users/search engines (SEO) etc.

### uBO version

N/A

### Browser name and version

N/A

### Operating system and version

N/A

**Comment by gorhill** [comment]
I prefer to decline, I just don't have the time to spend on this. Things are working just fine the way it is for all involved here, there is no need to fix what is not broken.

**Comment by garry-ut99** [comment]
Also a duplicate of:
- https://github.com/uBlockOrigin/uBlock-issues/issues/3271

which was already refferenced in https://github.com/gorhill/uBlock/issues/3726
