### ISSUE TITLE
Allow an encoded embedded url to be visited without the tracker

### ISSUE THREAD

**Issue by SamHughes** [uBlockOrigin/uBlock-issues#524]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
This is an enhancement request. 

Frequently when I visit a site that is a known tracker, redirector, etc. UBlock warns me, which is awesome. Thanks! 

However, in most cases, there's a url embedded and encoded in the redirecting url. I end up decoding the big url, grabbing out the part I wanted to go to, and continuing on to the sub url. 

For example, in the url below, I decode that and grab out just the part I want:
https://www.ticketmaster.com/tedeschi-trucks-band-seattle-washington-05-23-2019/event/0F005622FF6D5C2D

and discard the evyy.net part

I'd like UBlock to decode the embedded URLs, and give me the option to bypass the tracker and go directly to the embedded url rather than allowing me to temporarily or permanently allowing me to visit the tracker site. 

### A specific URL where the issue occurs
This came from clicking a link in Spotify, but this sort of thing is everywhere. 
http://ticketmaster.evyy.net/c/296934/271177/4272?sharedId=entity&subId1=005b2ebb44649dcc088c86d995fd49a5190a35792527efd0c69a17&subId3=2bvHZDQWxc7No46tTkPiYT&u=https%3A%2F%2Fwww.ticketmaster.com%2Ftedeschi-trucks-band-seattle-washington-05-23-2019%2Fevent%2F0F005622FF6D5C2D

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Visit a site with a banned/filtered redirect
2. Get warning: "uBlock Origin has prevented the following page from loading:"  

### Expected behavior:
It works fine right now, but I'd like to be able to visit the URL embedded within the tracker site's URL. 

### Actual behavior:

"uBlock Origin has prevented the following page from loading:"
yay awesome! :) We can do better. 

### Your environment

* uBlock Origin version: 1.18.16
* Browser Name and version: Firefox Quantum 60.6.1
* Operating System and version: Mac OS Mojave 10.14.4

**Comment by uBlock-user** [comment]
It already does the decoding part and offers the url too, all you have to do is click on it.

![](https://i.gyazo.com/c0b7eff48f2508dc0fedddf6304c9989.png)

**Comment by SamHughes** [comment]
Oh you are right! Didn't see the invisible plus button on the right until you said that.
